export const CUSTOM_WEB_APP_DEV_SERVICES = [
  {
    image_src: "/enterprise-web-app.png",
    title: "Enterprise Web Apps",
    text: "Managing large industries is crucial in this evolving world of modern technology. To make it accessible and considerable web apps support end-users to manage internal and external requirements from code to launch as required by modern web trends. Furnishing innovative web solutions Dignite’s top developer team drives your way to more structured and improved web applications, which results in producing huge business growth.",
    alt_tag: "",
    img_title: "",
  },
  {
    image_src: "/web-portal.png",
    title: "Web Portal",
    text: "Forming intuitive web portals seems a mere compulsion of businesses. It contains authorized access to accumulate tons of viable content for their client, vendors, and employees. Experience top customer web portal with our highly demanded experts who fabricate unbeatable web-based solutions for your thrilling web projects under a low-cost development budget and development time.",
    alt_tag: "",
    img_title: "",
  },
  {
    image_src: "/web-app-consultation.png",
    title: "Web App Consultation",
    text: "The consultation process indicates e-business direction, opportunities, risks, developmental methodologies, and marketing strategies to form the right decision at the right time. Consult top web solutions with Dignite’s development team to build scalable web development project planning according to its scope, value, and user engagements to propel your development practices.",
    alt_tag: "",
    img_title: "",
  },
  {
    image_src: "/custom-web-app.png",
    title: "Custom Web Application",
    text: "The art and science of custom web apps prevail in the unique infrastructure of web apps that form unique web app interfaces, dimensions, and developed web solutions to meet the distinct needs of businesses or large industries. Explore Dignite’s top-level tailored solutions to ensure web app development success that yields high investment distinction and compatibility across varied devices.",
    alt_tag: "",
    img_title: "",
  },
  {
    image_src: "/progressive-web-app.png",
    title: "Progressive Web App Development",
    text: "It is similar to platform-specific apps, you can run on multiple platforms with a single code, while also being offline. In developing web application design of Progressive apps modern web platform technologies are used to improve its capability and reliability to make it more responsive. Experience seamless navigation, exquisite functionalities, and modern features of web apps at Dignite Studios.",
    alt_tag: "",
    img_title: "",
  },
  {
    image_src: "/cross-platform-web-app.png",
    title: "Cross-Platform Web App Development",
    text: "Cross-platform apps won’t rely on two or more versions for Android, iOS, and the web has apparent benefits for its users. You can easily launch your application faster under cost-effective measures for your diversity.",
    alt_tag: "",
    img_title: "",
  },
  {
    image_src: "/single-page-web-app.png",
    title: "Single-Page Web Apps",
    text: "A single-page application loads a single document and rewrites the page with new content fetched from a browser. It has a vast popularity among businesses to adopt single-page applications. As it contains less time frame, a simple app layout, smooth navigation, and utilization of resources. We construct web apps with modified strategies, frameworks, and dynamic architecture of web design to attain business goals ona a wider scale.",
    alt_tag: "",
    img_title: "",
  },
  {
    image_src: "/ecommerce-web-app.png",
    title: "E-commerce Web App Development",
    text: "Revolutionize your online presence with strong e-commerce large-scale web applications. Such apps are more immersive and represent engaging fast-performing web software for the users. It also offers more personalized features for high engagement rates and ROIs. To robust your web development project goals with the latest  business dimensions, schedule a call with Dignite’s highly professional experts features of the web app and establish it more personalized with offline access.",
    alt_tag: "",
    img_title: "",
  },
];
