"use client"
import { GlobalContext } from '@/context/GlobalContext'
import React, { useContext } from 'react'

const TermsPage = () => {
    const { palette } = useContext(GlobalContext)
    return (
        <div className='w-full h-auto flex flex-col gap-4 justify-start items-start px-4 md:px-12 lg:px-64 lg:pb-10' style={{
            background: palette?.background,
            color: palette?.color
        }}>
            <h1 className='text-[45px] font-extrabold lg:text-[55px]  lg:font-bold uppercase'>Terms & Conditions</h1>
            <div>
                <h3 className='text-xl font-bold mt-5'><span >General Terms</span></h3>
                <p className='text-md font-medium'>
                    By accessing and placing an order with Dignite Studios, you confirm that you are in agreement with and
                    bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the
                    entire website and any email or other type of communication between you and Dignite Studios.
                    <br />
                    <br />
                    Under no circumstances shall Dignite Studios team be liable for any direct, indirect, special, incidental or
                    consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the
                    inability to use, the materials on this site, even if Dignite Studios team or an authorized representative has
                    been advised of the possibility of such damages. If your use of materials from this site results in the need for
                    servicing, repair or correction of equipment or data, you assume any costs thereof.
                    <br />
                    <br />
                    Dignite Studios will not be responsible for any outcome that may occur during the course of usage of our
                    resources. We reserve the rights to change prices and revise the resources usage policy in any moment.
                </p>
                <h3 className='text-xl font-bold mt-5'><span >License</span></h3>
                <p className='text-md font-medium'>
                    Dignite Studios grants you a revocable, non-exclusive, non-transferable, limited license to download, install
                    and use the website strictly in accordance with the terms of this Agreement.<br />
                    <br />
                    These Terms & Conditions are a contract between you and Dignite Studios (referred to in these Terms &
                    Conditions as "Dignite Studios", "us", "we" or "our"), the provider of the Dignite Studios website and the
                    services accessible from the Dignite Studios website (which are collectively referred to in these Terms &
                    Conditions as the "Dignite Studios Service").<br />
                    <br />
                    You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms &
                    Conditions, please do not use the Dignite Studios Service. In these Terms & Conditions, "you" refers both to
                    you as an individual and to the entity you represent. If you violate any of these Terms & Conditions, we
                    reserve the right to cancel your account or block access to your account without notice.


                </p>
                <h3 className='text-xl font-bold mt-5'><span >Definitions and key terms</span></h3>

                <p className='text-md font-medium'>

                    To help explain things as clearly as possible in this Terms & Conditions, every time any of these terms are
                    referenced, are strictly defined as:
                    <ul className='ml-4 list-disc'>
                        <li>

                            Cookie: small amount of data generated by a website and saved by your web browser. It is used to
                            identify your browser, provide analytics, remember information about you such as your language
                            preference or login information.
                        </li>
                        <li>

                            Company: when this terms mention “Company,” “we,” “us,” or “our,” it refers to Dignite Studios , (3505
                            Lake Lynda Dr #200, Orlando, FL 32817, United States), that is responsible for your information under
                            this Terms & Conditions.
                        </li>
                        <li>

                            Country: where Dignite Studios or the owners/founders of Dignite Studios are based, in this case is
                            United States of America
                        </li>
                        <li>

                            Device: any internet connected device such as a phone, tablet, computer or any other device that can
                            be used to visit Dignite Studios and use the services.
                        </li>
                        <li>

                            Service: refers to the service provided by Dignite Studios as described in the relative terms (if available)
                            and on this platform.
                        </li>
                        <li>

                            Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and
                            others who provide our content or whose products or services we think may interest you.
                        </li>
                        <li>

                            Website: Dignite Studios’s site, which can be accessed via this URL: dignitestudios.com
                        </li>
                        <li>

                            You: a person or entity that is registered with Dignite Studios to use the Services.
                        </li>
                    </ul>

                </p>
                <h3 className='text-xl font-bold mt-5'><span >Restrictions</span></h3>

            </div>
        </div>
    )
}

export default TermsPage