"use client";
import { GlobalContext } from "@/context/GlobalContext";
import React, { useContext } from "react";
import { motion } from "framer-motion";
import { staggerContainer, bgVariant } from "@/lib/motion";
import VerticalTimeline from "../mobile-app-california/VerticalTimeline";


const WaterfallProcess = () => {
  const { palette } = useContext(GlobalContext);
  return (
    <>
      <div className="w-full my-6 px-2 lg:px-10 xl:px-14 h-auto hidden lg:flex flex-col lg:flex-row gap-0 lg:gap-10 justify-start items-start">
        <div className=" w-full lg:w-[49%] h-auto grid grid-rows-3 grid-cols-1 gap-3">
          <div className="group  w-full h-auto lg:h-auto border-b-[1px] border-[#b4b4b4]/[0.5] flex flex-col justify-center items-start  py-10">
            <p className="transition-all duration-150 text-[#F15C20] text-[70px] lg:text-[100px] xl:text-[114px] font-bold leading-[137.97px]">
              01.
            </p>
            <h4 className="text-[40px] lg:text-[48px] font-bold uppercase leading-[58.09px]">
              Brainstorming
            </h4>
            <h5 className="capitalize text-[30px] lg:text-[36px] font-semibold leading-[43.57px] xl:font-medium text-[#F15C20]">
              Planning & Research
            </h5>
            <p
              className="text-[14px] font-normal  2xl:text-[18px] "
              style={{ color: palette?.light_contrast_color }}
            >
              Before executing a mobile app, our mobile app development experts
              articulate a proper guideline for how your app serves your users
              and meets the needs of a company. We also help in accessing
              perfect application solutions and the budget to develop your
              mobile app. So, to kick start the entire operational work
              according to the master plan generated by our valuable developers,
              simply schedule a call at once. 
            </p>
          </div>
          <div className="group  w-full h-auto lg:h-auto   border-b-[1px] border-[#b4b4b4]/[0.5] flex flex-col justify-center items-start  py-10">
            <p className="transition-all duration-150 text-[#F15C20] text-[70px] lg:text-[100px] xl:text-[114px] font-bold leading-[137.97px]">
              03.
            </p>
            <h4 className="text-[40px] lg:text-[48px] font-bold uppercase leading-[58.09px]">
              Aesthetics
            </h4>
            <h5 className="capitalize text-[30px] lg:text-[36px] font-semibold leading-[43.57px] xl:font-medium text-[#F15C20]">
              User Interface Design
            </h5>
            <p
              className="text-[14px] font-normal  2xl:text-[18px] "
              style={{ color: palette?.light_contrast_color }}
            >
              Unique visual appearance incorporates interactive features to your
              website and web application process which encompasses a
              user-friendly interface that reflects the target audience.
            </p>
          </div>
          <div className="group  w-full h-auto lg:h-auto  flex flex-col justify-center items-start  py-10">
            <p className="transition-all duration-150 text-[#F15C20] text-[70px] lg:text-[100px] xl:text-[114px] font-bold leading-[137.97px]">
              05.
            </p>
            <h4 className="text-[40px] lg:text-[48px] font-bold uppercase leading-[58.09px]">
              Back End
            </h4>
            <h5 className="capitalize text-[30px] lg:text-[36px] font-semibold leading-[43.57px] xl:font-medium text-[#F15C20]">
              Testing & Evaluation
            </h5>
            <p
              className="text-[14px] font-normal  2xl:text-[18px] "
              style={{ color: palette?.light_contrast_color }}
            > 
              Our expert developers will store all your application data and
              infrastructure to make it work properly. Database servers apply
              API to provide additional features to the third party to modify
              the relevant data.
            </p>
          </div>
        </div>
        {/* <div className="hidden lg:grid w-auto h-[80rem] grid-rows-5 grid-cols-1 justify-center items-start">
          <motion.span
            variants={staggerContainer}
            initial="hidden"
            whileInView="show"
            viewport={{ once: false, amount: 0.25 }}
            className=" h-full  flex flex-col justify-start items-center"
          >
            <motion.span
              variants={bgVariant("#B4B4B4", "black", "tween", 0.5, 5)}
              viewport={{ once: false, amount: 0.25 }}
              className=" w-[32px] h-[32px] rounded-full   flex items-center justify-center"
              style={{ background: palette?.color }}
            >
              <motion.span
                variants={bgVariant("#fff", "#fff", "tween", 0, 5)}
                viewport={{ once: false, amount: 0.25 }}
                className="w-2 h-2 rounded-full "
                style={{ background: palette?.background }}
              ></motion.span>
            </motion.span>
            <motion.span
              variants={bgVariant("#B4B4B4", "black", "tween", 0.5, 5)}
              viewport={{ once: false, amount: 0.25 }}
              className="h-[calc(100%-64px)] w-[2px] "
              style={{ background: palette?.color }}
            ></motion.span>
            <motion.span
              variants={bgVariant("#B4B4B4", "black", "tween", 0.5, 5)}
              viewport={{ once: false, amount: 0.25 }}
              className=" w-[32px] h-[32px] rounded-full   flex items-center justify-center"
              style={{ background: palette?.color }}
            >
              <motion.span
                variants={bgVariant("#fff", "#fff", "tween", 0, 5)}
                viewport={{ once: false, amount: 0.25 }}
                className="w-2 h-2 rounded-full "
                style={{ background: palette?.background }}
              ></motion.span>
            </motion.span>
          </motion.span>
          <motion.span
            variants={staggerContainer}
            initial="hidden"
            whileInView="show"
            viewport={{ once: false, amount: 0.25 }}
            className=" h-full  flex flex-col justify-start items-center"
          >
            <motion.span
              variants={bgVariant("#B4B4B4", "black", "tween", 0.5, 5)}
              viewport={{ once: false, amount: 0.25 }}
              className="h-[calc(100%-1.5rem)] w-[2px] bg-[#b4b4b4]/[0.5]"
            ></motion.span>
            <motion.span
              variants={bgVariant("#B4B4B4", "black", "tween", 0.5, 5)}
              viewport={{ once: false, amount: 0.25 }}
              className=" w-[32px] h-[32px] rounded-full   flex items-center justify-center"
              style={{ background: palette?.color }}
            >
              <motion.span
                variants={bgVariant("#fff", "#fff", "tween", 0, 5)}
                viewport={{ once: false, amount: 0.25 }}
                className="w-2 h-2 rounded-full "
                style={{ background: palette?.background }}
              ></motion.span>
            </motion.span>
          </motion.span>
          <motion.span
            variants={staggerContainer}
            initial="hidden"
            whileInView="show"
            viewport={{ once: false, amount: 0.25 }}
            className=" h-full  flex flex-col justify-start items-center">
            <motion.span
              variants={bgVariant("#B4B4B4", "black", "tween", 0.5, 5)}
              viewport={{ once: false, amount: 0.25 }}
              className="h-[calc(100%-1.5rem)] w-[2px] bg-[#b4b4b4]/[0.5]"></motion.span>
            <motion.span
              variants={bgVariant("#B4B4B4", "black", "tween", 0.5, 5)}
              viewport={{ once: false, amount: 0.25 }}
              className=" w-[32px] h-[32px] rounded-full   flex items-center justify-center"
              style={{ background: palette?.color }}>
              <motion.span
                variants={bgVariant("#fff", "#fff", "tween", 0, 5)}
                viewport={{ once: false, amount: 0.25 }}
                className="w-2 h-2 rounded-full "
                style={{ background: palette?.background }}></motion.span>
            </motion.span>
          </motion.span>
          <motion.span
            variants={staggerContainer}
            initial="hidden"
            whileInView="show"
            viewport={{ once: false, amount: 0.25 }}
            className=" h-full  flex flex-col justify-start items-center"
          >
            <motion.span
              variants={bgVariant("#B4B4B4", "black", "tween", 0.5, 5)}
              viewport={{ once: false, amount: 0.25 }}
              className="h-[calc(100%-1.5rem)] w-[2px] bg-[#b4b4b4]/[0.5]"
            ></motion.span>
            <motion.span
              variants={bgVariant("#B4B4B4", "black", "tween", 0.5, 5)}
              viewport={{ once: false, amount: 0.25 }}
              className=" w-[32px] h-[32px] rounded-full   flex items-center justify-center"
              style={{ background: palette?.color }}
            >
              <motion.span
                variants={bgVariant("#fff", "#fff", "tween", 0, 5)}
                viewport={{ once: false, amount: 0.25 }}
                className="w-2 h-2 rounded-full "
                style={{ background: palette?.background }}
              ></motion.span>
            </motion.span>
          </motion.span>
          <motion.span
            variants={staggerContainer}
            initial="hidden"
            whileInView="show"
            viewport={{ once: false, amount: 0.25 }}
            className=" h-full  flex flex-col justify-start items-center"
          >
            <motion.span
              variants={bgVariant("#B4B4B4", "black", "tween", 0.5, 5)}
              viewport={{ once: false, amount: 0.25 }}
              className="h-[calc(100%-1.5rem)] w-[2px] bg-[#b4b4b4]/[0.5]"
            ></motion.span>
            <motion.span
              variants={bgVariant("#B4B4B4", "black", "tween", 0.5, 5)}
              viewport={{ once: false, amount: 0.25 }}
              className=" w-[32px] h-[32px] rounded-full   flex items-center justify-center"
              style={{ background: palette?.color }}
            >
              <motion.span
                variants={bgVariant("#fff", "#fff", "tween", 0, 5)}
                viewport={{ once: false, amount: 0.25 }}
                className="w-2 h-2 rounded-full "
                style={{ background: palette?.background }}
              ></motion.span>
            </motion.span>
          </motion.span>
        </div> */}
        <VerticalTimeline palette={palette} />
        <div className="w-full lg:w-[49%] h-auto lg:mt-44 grid grid-rows-3 grid-cols-1 gap-3">
          <div className="group  w-full h-auto lg:h-auto   border-b-[1px] border-[#b4b4b4]/[0.5] flex flex-col justify-center items-start  py-10">
            <p className="transition-all duration-150 text-[#F15C20] text-[70px] lg:text-[100px] xl:text-[114px] font-bold leading-[137.97px]">
              02.
            </p>
            <h4 className="text-[40px] lg:text-[48px] font-bold uppercase leading-[58.09px]">
              Structure
            </h4>
            <h5 className="capitalize text-[30px] lg:text-[36px] font-semibold leading-[43.57px] xl:font-medium text-[#F15C20]">
              Foundation & UX
            </h5>
            <p
              className="text-[14px] font-normal  2xl:text-[18px] "
              style={{ color: palette?.light_contrast_color }}
            >
              Our dedicated mobile app development team creates your mobile
              application ideas and web application development structure well-
              which includes formal stages like planning, designing,
              outsourcing, coding, testing, marketing, maintenance, support, and
              deployment to maintain a monetization on the initial requirements
              of mobile apps.
            </p>
          </div>
          <div className="group  w-full h-auto lg:h-auto   border-b-[1px] border-[#b4b4b4]/[0.5] flex flex-col justify-center items-start  py-10">
            <p className="transition-all duration-150 text-[#F15C20] text-[70px] lg:text-[100px] xl:text-[114px] font-bold leading-[137.97px]">
              04.
            </p>
            <h4 className="text-[40px] lg:text-[48px] font-bold uppercase leading-[58.09px]">
              Front End
            </h4>
            <h5 className="capitalize text-[30px] lg:text-[36px] font-semibold leading-[43.57px] xl:font-medium text-[#F15C20]">
              Development
            </h5>
            <p
              className="text-[14px] font-normal  2xl:text-[18px] "
              style={{ color: palette?.light_contrast_color }}
            >
              The front end is developed according to the user requirement and
              incorporates the front screen of your application interface
              including graphics, text messages, buttons, checkboxes, and other
              features. To make it highly effective our team members dynamically
              systemize Swift, Flutter, React Native, Java, and Kotlin.
            </p>
          </div>
          <div className="group  w-full h-auto lg:h-auto  flex flex-col justify-center items-start  py-10">
            <p className="transition-all duration-150 text-[#F15C20] text-[70px] lg:text-[100px] xl:text-[114px] font-bold leading-[137.97px]">
              06.
            </p>
            <h4 className="text-[40px] lg:text-[48px] font-bold uppercase leading-[58.09px]">
              Jackpot
            </h4>
            <h5 className="capitalize text-[30px] lg:text-[36px] font-semibold leading-[43.57px] xl:font-medium text-[#F15C20]">
              Go Live
            </h5>
            <p
              className="text-[14px] font-normal  2xl:text-[18px] "
              style={{ color: palette?.light_contrast_color }}
            >
              Here at Dignite Studios, developers use a systematic approach to
              improving the algorithms before the deployment process. These
              adjustments ensure a smooth and responsive environment for each
              visual element and an immersive experience of the user interface.
              Further, our experts proceed with the launching of the application
              by deploying it on the iOS store and Google Play store with a
              proper documentation process.
            </p>
          </div>
        </div>
      </div>

      <div className="w-full my-6 px-2 lg:px-10 h-auto lg:hidden flex flex-col lg:flex-row gap-0 lg:gap-10 justify-start items-start">
        <div className=" w-full lg:w-[49%] h-auto grid grid-rows-3 grid-cols-1 gap-3">
          <div className="group  w-full h-auto lg:h-auto   border-b-[1px] border-[#b4b4b4]/[0.5] flex flex-col justify-center items-start  pb-3 lg:py-10">
            <p className="transition-all duration-150 text-[#F15C20] text-[70px] lg:text-[100px] xl:text-[114px] font-bold leading-[4.5rem] xl:leading-[137.97px]">
              01.
            </p>
            <h4 className="text-[40px] lg:text-[48px] font-bold uppercase leading-[58.09px]">
              Brainstorming
            </h4>
            <h5 className="capitalize text-[30px] lg:text-[36px] font-semibold leading-[43.57px] xl:font-medium text-[#F15C20]">
              Planning & Research
            </h5>
            <p
              className="text-[14px] font-normal  2xl:text-[18px] "
              style={{ color: palette?.light_contrast_color }}
            >
              Before executing a mobile app, our mobile app development experts
              articulate a proper guideline for how your app serves your users
              and meets the needs of a company. We also help in accessing
              perfect application solutions and the budget to develop your
              mobile app. So, to kick start the entire operational work
              according to the master plan generated by our valuable developers,
              simply schedule a call at once.  
            </p>
          </div>
          <div className="group  w-full h-auto lg:h-auto   border-b-[1px] border-[#b4b4b4]/[0.5] flex flex-col justify-center items-start  pb-3 lg:py-10">
            <p className="transition-all duration-150 text-[#F15C20] text-[70px] lg:text-[100px] xl:text-[114px] font-bold leading-[4.5rem] xl:leading-[137.97px]">
              02.
            </p>
            <h4 className="text-[40px] lg:text-[48px] font-bold uppercase leading-[58.09px]">
              Structure
            </h4>
            <h5 className="capitalize text-[30px] lg:text-[36px] font-semibold leading-[43.57px] xl:font-medium text-[#F15C20]">
              Foundation & UX
            </h5>
            <p
              className="text-[14px] font-normal  2xl:text-[18px] "
              style={{ color: palette?.light_contrast_color }}
            >
              Our dedicated mobile app development team creates your mobile
              application ideas and web application development structure well-
              which includes formal stages like planning, designing,
              outsourcing, coding, testing, marketing, maintenance, support, and
              deployment to maintain a monetization on the initial requirements
              of mobile apps.
            </p>
          </div>
          <div className="group  w-full h-auto lg:h-auto  border-b-[1px] border-[#b4b4b4]/[0.5] flex flex-col justify-center items-start  pb-3 lg:py-10">
            <p className="transition-all duration-150 text-[#b4b4b4]/[0.7] text-[70px] lg:text-[100px] group-hover:text-[#F15C20] font-bold leading-[4.5rem]">
              03.
            </p>
            <h4 className="text-[40px] lg:text-[48px] font-bold uppercase leading-[58.09px]">
              Aesthetics
            </h4>
            <h5 className="capitalize text-[30px] lg:text-[36px] font-semibold leading-[43.57px] xl:font-medium text-[#F15C20]">
              User Interface Design
            </h5>
            <p
              className="text-[14px] font-normal  2xl:text-[18px] "
              style={{ color: palette?.light_contrast_color }}
            >
              Unique visual appearance incorporates interactive features to your
              website and web application process which encompasses a
              user-friendly interface that reflects the target audience.
            </p>
          </div>
        </div>
        <div className="hidden lg:grid w-auto h-[80rem] grid-rows-5 grid-cols-1 justify-center items-start">
          <span className=" h-full  flex flex-col justify-start items-center">
            <span
              className=" w-[32px] h-[32px] rounded-full   flex items-center justify-center"
              style={{ background: palette?.color }}
            >
              <span
                className="w-2 h-2 rounded-full "
                style={{ background: palette?.background }}
              ></span>
            </span>
            <span
              className="h-[calc(100%-64px)] w-[2px] "
              style={{ background: palette?.color }}
            ></span>
            <span
              className=" w-[32px] h-[32px] rounded-full   flex items-center justify-center"
              style={{ background: palette?.color }}
            >
              <span
                className="w-2 h-2 rounded-full "
                style={{ background: palette?.background }}
              ></span>
            </span>
          </span>
          <span className=" h-full  flex flex-col justify-start items-center">
            <span className="h-[calc(100%-1.5rem)] w-[2px] bg-[#b4b4b4]/[0.5]"></span>
            <span className=" w-[32px] h-[32px] rounded-full bg-[#b4b4b4]/[0.5]  flex items-center justify-center">
              <span
                className="w-2 h-2 rounded-full "
                style={{ background: palette?.background }}
              ></span>
            </span>
          </span>
          <span className=" h-full  flex flex-col justify-start items-center">
            <span className="h-[calc(100%-1.5rem)] w-[2px] bg-[#b4b4b4]/[0.5]"></span>
            <span className=" w-[32px] h-[32px] rounded-full bg-[#b4b4b4]/[0.5]  flex items-center justify-center">
              <span
                className="w-2 h-2 rounded-full "
                style={{ background: palette?.background }}
              ></span>
            </span>
          </span>
          <span className=" h-full  flex flex-col justify-start items-center">
            <span className="h-[calc(100%-1.5rem)] w-[2px] bg-[#b4b4b4]/[0.5]"></span>
            <span className=" w-[32px] h-[32px] rounded-full bg-[#b4b4b4]/[0.5]  flex items-center justify-center">
              <span
                className="w-2 h-2 rounded-full "
                style={{ background: palette?.background }}
              ></span>
            </span>
          </span>
          <span className=" h-full  flex flex-col justify-start items-center">
            <span className="h-[calc(100%-1.5rem)] w-[2px] bg-[#b4b4b4]/[0.5]"></span>
            <span className=" w-[32px] h-[32px] rounded-full bg-[#b4b4b4]/[0.5]  flex items-center justify-center">
              <span
                className="w-2 h-2 rounded-full "
                style={{ background: palette?.background }}
              ></span>
            </span>
          </span>
        </div>
        <div className="w-full lg:w-[49%] h-auto lg:mt-44 grid grid-rows-3 grid-cols-1 gap-3">
          <div className="group  w-full h-auto lg:h-auto border-b-[1px] border-[#b4b4b4]/[0.5] flex flex-col justify-center items-start  pb-3 lg:py-10">
            <p className="transition-all duration-150 text-[#F15C20] text-[70px] lg:text-[100px] xl:text-[114px] font-bold leading-[4.5rem] xl:leading-[137.97px]">
              04.
            </p>
            <h4 className="text-[40px] lg:text-[48px] font-bold uppercase leading-[58.09px]">
              Front End
            </h4>
            <h5 className="capitalize text-[30px] lg:text-[36px] font-semibold leading-[43.57px] xl:font-medium text-[#F15C20]">
              Development
            </h5>
            <p
              className="text-[14px] font-normal  2xl:text-[18px] "
              style={{ color: palette?.light_contrast_color }}
            >
              The front end is developed according to the user requirement and
              incorporates the front screen of your application interface
              including graphics, text messages, buttons, checkboxes, and other
              features. To make it highly effective our team members dynamically
              systemize Swift, Flutter, React Native, Java, and Kotlin.
            </p>
          </div>
          <div className="group  w-full h-auto lg:h-auto   border-b-[1px] border-[#b4b4b4]/[0.5] flex flex-col justify-center items-start  pb-3 lg:py-10">
            <p className="transition-all duration-150 text-[#b4b4b4]/[0.7] text-[70px] lg:text-[100px] group-hover:text-[#F15C20] font-bold leading-[4.5rem]">
              05.
            </p>
            <h4 className="text-[40px] lg:text-[48px] font-bold uppercase leading-[58.09px]">
              Back End
            </h4>
            <h5 className="capitalize text-[30px] lg:text-[36px] font-semibold leading-[43.57px] xl:font-medium text-[#F15C20]">
              Testing & Evaluation
            </h5>
            <p
              className="text-[14px] font-normal  2xl:text-[18px] "
              style={{ color: palette?.light_contrast_color }}
            >
              Our expert developers will store all your application data and
              infrastructure to make it work properly. Database servers apply
              API to provide additional features to the third party to modify
              the relevant data.
            </p>
          </div>
          <div className="group  w-full h-auto lg:h-auto  flex flex-col justify-center items-start  pb-3 lg:py-10">
            <p className="transition-all duration-150 text-[#F15C20] text-[70px] lg:text-[100px] xl:text-[114px] font-bold leading-[4.5rem] xl:leading-[137.97px]">
              06.
            </p>
            <h4 className="text-[40px] lg:text-[48px] font-bold uppercase leading-[58.09px]">
              Jackpot
            </h4>
            <h5 className="capitalize text-[30px] lg:text-[36px] font-semibold leading-[43.57px] xl:font-medium text-[#F15C20]">
              Go Live
            </h5>
            <p
              className="text-[14px] font-normal  2xl:text-[18px] "
              style={{ color: palette?.light_contrast_color }}
            >
              Here at Dignite Studios, developers use a systematic approach to
              improving the algorithms before the deployment process. These
              adjustments ensure a smooth and responsive environment for each
              visual element and an immersive experience of the user interface.
              Further, our experts proceed with the launching of the application
              by deploying it on the iOS store and Google Play store with a
              proper documentation process.
            </p>
          </div>
        </div>
      </div>
    </>
  );
};

export default WaterfallProcess;
